### ISSUE TITLE
Error in the "Introduction to Free Monads" blog post

### ISSUE THREAD

**Issue by kukimik** [serokell/blog-posts#10]
@lierdakil This was a [Reddit comment](https://www.reddit.com/r/haskell/comments/shulfo/comment/hvkikhg/?utm_source=share&utm_medium=web2x&context=3), but then I found this repo and decided it's better to create an issue.

The following sentence in the blog post [Introduction to Free Monads](https://github.com/serokell/blog-posts/blob/master/Introduction%20to%20Free%20Monads/article.md) is wrong.

> On the other hand, addition over non-negative integers doesn’t constitute a free monoid. That would imply the law of commutativity, which isn’t a monoid law.

Non-negative integers under addition are a free monoid (which is isomorphic to the list monoid described in the blog post, given that the generator set `S` is a singleton). Because there is a single generator (so any element is of the form `s^n`), the commutativity relation follows from associativity.

The intuition _"The only laws that hold for the generated structure are those required to hold."_ is right, but as long as you don't want to get into the details of generators and relations, it's perhaps better expressed in terms of homomorphisms (i.e. structure-preserving functions: `f(x<>y) = f(x)<>f(y)`). If `M` is a free monoid over `S`, then for any monoid `X` and any function `f: S -> X` we can extend this function to a homomorphism `f': M -> X`. (And the minimality condition basically says that there is only one such homomorphism.)

---------------

I'm also not sure if "vague" is the best word here:

> The exact definition of “minimal” in abstract algebra is a little vague

I believe the exact definition in abstract algebra is rather precise. It's the article that does some handwaving (which I don't see as anything wrong by itself).

**Comment by lierdakil** [comment]
> The following sentence in the blog post Introduction to Free Monads is wrong

Uh. That it is. Thanks for bringing this up. I didn't think this through, "non-negative" is misplaced there, since, as you say, commutativity is implied by associativity for naturals.

> perhaps better expressed in terms of homomorphisms

Maybe, but I feel it's a bit too abstract for a casual reader. Then again, that whole section probably is.

> I'm also not sure if "vague" is the best word here

FWIW, I'm parroting [the Haskell wiki](https://wiki.haskell.org/Free_structure#Free_structure_functors) here. I can't claim to be proficient enough in abstract nonsense to really dispute this.
