### ISSUE TITLE
Add Grammatical Framework to "Open-Source Haskell: Awesome Projects, Tools, and Libraries"

### ISSUE THREAD

**Issue by inariksit** [serokell/blog-posts#22]
Grammatical Framework (GF, http://www.grammaticalframework.org) is a domain-specific programming language for writing multilingual natural language grammars. GF's compiler is written in Haskell, see https://github.com/GrammaticalFramework/gf-core/tree/master/src/compiler.

From the beginning (in 1998), all of GF—compiler, shell, runtime—was written purely in Haskell. This codebase is still in active use, but these days we have an additional C runtime with bindings to other programming languages like Python.

**Comment by NaeosPsy** [comment]
Thanks, I've added it to the compiler section of the article.  👍
