### ISSUE TITLE
Add Lamdu to compilers section in "Open-Source Haskell: Awesome Projects, Tools, and Libraries"

### ISSUE THREAD

**Issue by yairchu** [serokell/blog-posts#24]
[Lamdu](https://lamdu.org/) is a projectional programming language implemented in Haskell. While its compiler isn't a traditional one involving parsing, it does have type-inference and transpilation of the core language to JavaScript and to the sugared surface language.

**Comment by NaeosPsy** [comment]
I've updated the post with the language, thank you for the suggestion!
